# Generated by Django 4.2 on 2023-04-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField(max_length=150)),
                ('ano', models.CharField(max_length=150)),
                ('duracao', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=150)),
                ('bilheteria', models.CharField(max_length=150)),
            ],
        ),
    ]
