# Generated by Django 4.2 on 2023-04-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_registration_app', '0003_alter_filmes_bilheteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='acoes',
        ),
    ]
