# Generated by Django 4.2 on 2023-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_registration_app', '0005_alter_filmes_ano_alter_filmes_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='ano',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='filmes',
            name='duracao',
            field=models.CharField(max_length=150),
        ),
    ]
