# Generated by Django 4.2 on 2023-04-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_registration_app', '0006_alter_filmes_ano_alter_filmes_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='bilheteria',
            field=models.CharField(max_length=100),
        ),
    ]
