# Generated by Django 4.2 on 2023-04-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_registration_app', '0007_alter_filmes_bilheteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='premiacoes',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='sinopse',
        ),
    ]
